# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: electricityConsumption.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65lectricityConsumption.proto\"A\n\x10\x45\x43onsumptionData\x12\x19\n\x11timeofConsumption\x18\x01 \x01(\t\x12\x12\n\nmeterusage\x18\x02 \x01(\t\"\x15\n\x13\x45\x43onsumptionRequest\"I\n\x14\x45\x43onsumptionResponse\x12\x31\n\x16\x65lectricityConsumption\x18\x01 \x03(\x0b\x32\x11.EConsumptionData2\\\n\x16\x45lectricityConsumption\x12\x42\n\x13GetEConsumptionData\x12\x14.EConsumptionRequest\x1a\x15.EConsumptionResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'electricityConsumption_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECONSUMPTIONDATA._serialized_start=32
  _ECONSUMPTIONDATA._serialized_end=97
  _ECONSUMPTIONREQUEST._serialized_start=99
  _ECONSUMPTIONREQUEST._serialized_end=120
  _ECONSUMPTIONRESPONSE._serialized_start=122
  _ECONSUMPTIONRESPONSE._serialized_end=195
  _ELECTRICITYCONSUMPTION._serialized_start=197
  _ELECTRICITYCONSUMPTION._serialized_end=289
# @@protoc_insertion_point(module_scope)
