# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import electricityConsumption_pb2 as electricityConsumption__pb2


class ElectricityConsumptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEConsumptionData = channel.unary_unary(
                '/ElectricityConsumption/GetEConsumptionData',
                request_serializer=electricityConsumption__pb2.EConsumptionRequest.SerializeToString,
                response_deserializer=electricityConsumption__pb2.EConsumptionResponse.FromString,
                )


class ElectricityConsumptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEConsumptionData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElectricityConsumptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEConsumptionData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEConsumptionData,
                    request_deserializer=electricityConsumption__pb2.EConsumptionRequest.FromString,
                    response_serializer=electricityConsumption__pb2.EConsumptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ElectricityConsumption', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ElectricityConsumption(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEConsumptionData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ElectricityConsumption/GetEConsumptionData',
            electricityConsumption__pb2.EConsumptionRequest.SerializeToString,
            electricityConsumption__pb2.EConsumptionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
